import { Component } from '@angular/core';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Atividade2';
  categoria: string = '';
  filmesPorCategoria: { titulo: string, descricao: string, imagem: string }[] = [];

  buscarFilmes(categoria: string): void {
    this.filmesPorCategoria = this.inicializarFilmes(categoria);
  }

  private inicializarFilmes(categoria: string): { titulo: string, descricao: string, imagem: string }[] {

    switch (categoria.toLowerCase()) {
      case 'ação':
        return [
          { titulo: 'Velozes & Furiosos 10', descricao: 'No décimo filme da série Velozes & Furiosos e último da nova trilogia (Velozes 8, 9 e 10), ao longo de muitas missões e contra probabilidades que pareciam impossíveis, Dom Toretto (Vin Diesel) e sua família foram mais espertos e superaram todos os inimigos em seu caminho. Agora, eles devem desafiar o adversário mais letal que já enfrentaram. Alimentada pela vingança, uma ameaça terrível emerge das sombras do passado na forma de Dante (Jason Momoa), para destruir o mundo de Toretto e destruir tudo - e todos - que ele ama. Ele então, comandando novamente a equipe de corredores mais conhecida do mundo, encara mais uma difícil missão sobre quatro rodas. O fim da estrada começa e Velozes & Furiosos 10 lança os capítulos finais de uma das franquias globais mais famosas e populares do cinema, agora em sua terceira década e ainda forte com o mesmo elenco e personagens centrais de quando começou.', imagem: 'https://br.web.img3.acsta.net/c_310_420/pictures/23/05/16/22/53/0156803.jpg' },
          { titulo: 'Os Mercenários 4', descricao: 'No quarto filme da franquia Os Mercenários, a equipe enfrentará um traficante de armas que comanda um enorme exército privado. Munidos com todas as armas inimagináveis, os Mercenários são a última linha de defesa do mundo. Reunidos como a equipe de mercenários de elite, os veteranos comandados por Sylvester Stallone se juntam pela primeira vez a uma nova geração de estrelas. Os novos membros da equipe com novos estilos e táticas darão a "sangue novo" um significado totalmente novo. E quando a equipe é chamada para mais uma missão, é certo de que todas as outras opções seriam incapazes de cumprir o que só eles podem.', imagem: 'https://br.web.img2.acsta.net/c_310_420/pictures/23/07/05/19/26/0174226.jpg'},
          { titulo: 'Hulk', descricao: 'Bruce Banner (Eric Bana) é um cientista que teve problemas em sua infância: ele foi adotado e passou por uma experiência traumática após a morte de seus pais, a qual não lembra de forma alguma. Juntamente com ele trabalha Betty Ross (Jennifer Connelly), sua grande paixão. Ambos trabalham em um projeto que envolve a reconstituição de tecidos através da radiação gama, um projeto o qual o Exército está bastante interessado. Ao consertar o gammasphere, aparelho usado para aplicar a radiação gama em animais, um dos cientistas do projeto o aciona acidentalmente. Em uma tentativa desesperada de salvar o amigo, Banner se atira defronte o gammasphere e absorve a radiação gama lançada. Inexplicavelmente o acidente não o mata, fazendo com que permaneça durante algum tempo no hospital sob observação. É quando a reaparição de seu pai biológico, o qual considerava morto, revela segredos sobre o passado de Bruce Banner o qual nem ele mesmo conhecia, ao mesmo tempo em que precisa lidar com estranhas modificações em seu corpo a cada vez que fica com raiva.', imagem: 'https://br.web.img2.acsta.net/c_310_420/pictures/bzp/01/34509.jpg'},
          { titulo: 'Red - Aposentados e Perigosos', descricao: 'Em RED - Aposentados e Perigosos, Frank Moses (Bruce Willis) é um ex-agente da CIA, hoje aposentado, que tenta levar uma vida normal. Ele está interessado por Sarah (Mary-Louise Parker), com quem volta e meia conversa ao telefone, apesar de ainda não conhecer pessoalmente. Um dia, a casa de Frank é atacada por agentes da CIA. Sem saber o que está acontecendo, ele deduz que logo perceberão sua ligação com Sarah e parte para protegê-la. Para entender o porquê de ter sido atacado, Frank precisará da ajuda de seus antigos companheiros Joe (Morgan Freeman), Marvin (John Malkovich) e Victoria (Helen Mirren), todos também aposentados.', imagem: 'https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/87/90/72/19962771.jpg'},
          { titulo: 'Top Gun - Maverick', descricao: 'Na sequência de Top Gun: Ases Indomáveis, acompanhamos a história de Pete “Maverick” Mitchell (Tom Cruise), um piloto à moda antiga da Marinha que coleciona muitas condecorações, medalhas de combate e grande reconhecimento pela quantidade de aviões inimigos abatidos nos últimos 30 anos. Entretanto, nada disso foi suficiente para sua carreira decolar, visto que ele deixou de ser um capitão e tornou-se um instrutor. A explicação para esse declínio é simples: Ele continua sendo o mesmo piloto rebelde de sempre, que não hesita em romper os limites e desafiar a morte. Nesta nova aventura, Maverick precisa provar que o fator humano ainda é fundamental no mundo contemporâneo das guerras tecnológicas. Após 34 anos do clássico, acompanhem o filme do premiado produtor Jerry Bruckheimer e de Joseph Kosinski, mesmo diretor de Tron: O Legado (2010) e Oblivion (2013).', imagem: 'https://br.web.img3.acsta.net/c_310_420/pictures/19/12/16/15/00/5548914.jpg'}
        ];

      case 'terror':
        return [
          { titulo: 'A Freira', descricao: 'Fazendo parte da franquia Invocação do Mal, em A Freira, após uma irmã cometer suicídio em um convento na Romênia, o Vaticano envia um padre atormentado e uma noviça para investigar o ocorrido. Arriscando suas vidas, a fé e até suas almas, os dois descobrem um segredo profano no local, confrontando-se com uma força do mal que toma a forma de uma freira demoníaca e transforma o convento num campo de batalha espiritual.', imagem: 'https://br.web.img3.acsta.net/c_310_420/pictures/18/07/18/21/53/1348208.jpg' },
          { titulo: 'A Orfã', descricao: 'Kate (Vera Farmiga) e John Coleman (Peter Sarsgaard) ficam arrasados devido a um trágico aborto. Apesar de já ter dois filhos, Daniel (Jimmy Bennett) e a surda muda Maxime (Aryana Engineer), o casal decide adotar uma criança. Durante uma visita a um orfanato, os dois se encantam pela pequena Esther (Isabelle Fuhrman) de nove anos e optam rapidamente por sua adoção. O que eles não sabiam é que estranhos acontecimentos fazem parte do histórico da menina que passa a se tornar, dia após dia, mais misteriosa. Intrigada, Kate desconfia que Esther não é quem aparenta ser, mas devido ao seu passado de alcoolismo tem dificuldades de provar sua teoria.', imagem: 'https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/87/29/90/19874059.jpg' },
          { titulo: 'Jogos Mortais', descricao: 'Jigsaw é um assassino que possui uma marca registrada: ele deixa em suas vítimas uma cicatriz em forma de quebra-cabeças, que faz com que elas cometam atos igonizantes para se salvar. O detetive David Tapp (Danny Glover) é designado para investigar os assassinatos, bem como a capturar seu autor. Porém o caminho evasivo seguido por Jigsaw leva o detetive a desenvolver uma obsessão por capturá-lo.', imagem: 'https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/87/06/15/19871623.jpg' },
          { titulo: 'Zombeavers - terror no lago', descricao: 'Grupo de belos jovens universitários aproveita divertida estadia em uma cabana isolada de tudo e todos. O pesadelo começa quando eles são atacados por perigosos castores zumbis com sede de sangue.', imagem: 'https://br.web.img3.acsta.net/c_310_420/pictures/14/02/07/10/28/140617.jpg' },
          { titulo: 'Invocação do Mal', descricao: 'Harrisville, Estados Unidos. Um casal (Ron Livinston e Lili Taylor) muda para uma casa nova ao lado de suas cinco filhas. Inexplicavelmente, estranhos acontecimentos começam a assustar as crianças, o pai e, principalmente, a mãe. Preocupada com algumas manchas que aparecem em seu corpo e com uma sequência de sustos que levou, ela decide procurar um famoso casal de investigadores paranormais (Patrick Wilson e Vera Farmiga), mas eles não aceitam o convite, acreditando ser somente mais um engano de pessoas apavoradas com canos que fazem barulhos durante a noite ou coisas do gênero. Porém, quando eles aceitam fazer uma visita ao local, descobrem que algo muito poderoso e do mal reside ali. Agora, eles precisam descobrir o que é e o porquê daquilo tudo acontecendo com os membros daquela família. É quando o passado começa a revelar uma entidade demoníaca querendo continuar sua trajetória de maldades.', imagem: 'https://br.web.img3.acsta.net/c_310_420/pictures/210/166/21016629_2013062820083878.jpg' }
     ];
      
      case 'romance':
        return [
          { titulo: 'A Última Música', descricao: 'A Última Música acompanha a jovem Ronnie Miller (Miley Cyrus) que é filha de pais divorciados e seu pai (Greg Kinnear) mora longe de Nova York, numa cidade praiana. Após três anos de separação, ela ainda sente raiva por tudo o que aconteceu até o dia em que sua mãe (Kelly Preston) decide enviá-la para passar o verão com ele. Uma vez lá, depois de conhecer novas pessoas e paixões, ela encontra alguém que, além de bom músico e professor, é, acima de tudo, um verdadeiro pai.', imagem: 'https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/87/32/17/19874294.jpg' },
          { titulo: 'A Barraca do Beijo', descricao: 'Melhores amigos desde sempre, Elle (Joey King) e Lee (Joel Courtney) têm a inventiva ideia de gerenciar uma barraca do beijo durante um evento da escola. Para fazer da proposta um sucesso, a garota tenta convencer o galã Noah (Jacob Elordi), seu crush e irmão mais velho de Lee, a participar da brincadeira. Ele mostra-se irredutível, mas os dois acabam se aproximando como nunca, o que estremece a amizade de Elle e Lee.', imagem: 'https://br.web.img3.acsta.net/c_310_420/pictures/18/05/04/15/03/2133793.jpg' },
          { titulo: 'Continência ao Amor', descricao: 'Em Continência ao Amor, Cassie Salazar (Sofia Carson) é uma cantora em ascensão que quer sair da bolha. Para pagar o aluguel e suas doses de insulina, ela trabalha em um bar todas as noites com sua banda. Porém, suas doses diárias de remédio são muito caras e ela não consegue pagar um convênio médico e acaba atrasando outras contas para que consiga sobreviver. Isso até que ela vê em um contrato que, ao casar com um membro do exército dos EUA, o cônjuge ganha também um convênio médico e o salário aumenta. É com isso que ela conhece Luke Morrow (Nicholas Galitzine), um fuzileiro naval, que é parceiro de seu amigo de escola. Porém, ambos são de personalidades totalmente opostas, mas precisam forjar um casamento por conta de suas necessidades pessoais. Será que os dois conseguirão fingir um casamento amoroso por tanto tempo? Ou será que os dois vão acabar se apaixonando de verdade no processo?', imagem: 'https://br.web.img3.acsta.net/c_310_420/pictures/22/08/09/21/09/3949781.jpg' },
          { titulo: 'A Culpa é das Estrelas', descricao: 'Diagnosticada com câncer, a adolescente Hazel Grace Lancaster (Shailene Woodley) se mantém viva graças a uma droga experimental. Após passar anos lutando com a doença, ela é forçada pelos pais a participar de um grupo de apoio cristão. Lá, conhece Augustus Waters (Ansel Elgort), um rapaz que também sofre com câncer. Os dois possuem visões muito diferentes de suas doenças: Hazel preocupa-se apenas com a dor que poderá causar aos outros, já Augustus sonha em deixar a sua própria marca no mundo. Apesar das diferenças, eles se apaixonam. Juntos, atravessam os principais conflitos da adolescência e do primeiro amor, enquanto lutam para se manter otimistas e fortes um para o outro.', imagem: 'https://br.web.img3.acsta.net/c_310_420/pictures/14/01/23/14/12/101764.jpg' },
          { titulo: 'Como eu Era Antes de Você', descricao: 'Em Como Eu Era Antes de Você, o rico e bem sucedido Will (Sam Claflin) leva uma vida repleta de conquistas, viagens e esportes radicais até ser atingido por uma moto. O acidente o torna tetraplégico, obrigando-o a permanecer em uma cadeira de rodas. A situação o torna depressivo e extremamente cínico, para a preocupação de seus pais (Janet McTeer e Charles Dance). É neste contexto que Louisa Clark (Emilia Clarke) é contratada para cuidar de Will. De origem modesta, com dificuldades financeiras e sem grandes aspirações na vida, ela faz o possível para melhorar o estado de espírito de Will e, aos poucos, acaba se envolvendo com ele.', imagem: 'https://br.web.img3.acsta.net/c_310_420/pictures/16/02/03/19/11/303307.jpg' }
      ]; 

      case 'comédia':
        return [
          { titulo: 'O Auto da Compadecida', descricao: 'As aventuras dos nordestinos João Grilo (Matheus Natchergaele), um sertanejo pobre e mentiroso, e Chicó (Selton Mello), o mais covarde dos homens. Ambos lutam pelo pão de cada dia e atravessam por vários episódios enganando a todos do pequeno vilarejo de Taperoá, no sertão da Paraíba. A salvação da dupla acontece com a aparição da Nossa Senhora (Fernanda Montenegro). Adaptação da obra de Ariano Suassuna.', imagem: 'https://br.web.img2.acsta.net/c_310_420/medias/nmedia/18/87/87/75/19962458.jpg' },
          { titulo: 'Todo Mundo em Pânico', descricao: 'Das mentes dos criadores do seriado da TV americana "In living color" surge o primeiro thriller-comédia, em que adolescentes apavorados fugindo de maníacos assassinos são o pretexto para uma série de piadas envolvendo todos os recentes filme de terror, da série "Pânico" até "O sexto sentido", passando ainda por outros grandes sucessos do cinema, como "Matrix" e "Os suspeitos".', imagem: 'https://br.web.img2.acsta.net/c_310_420/medias/nmedia/18/87/28/03/19873867.jpg' },
          { titulo: 'Norbit', descricao: 'Norbit (Eddie Murphy) foi criado pelo sr. Wong (Eddie Murphy), que o encontrou ainda bebê no Restaurante e Orfanato Wonton Dourado. Foi neste local que ele conheceu sua alma gêmea, Kate (Thandie Newton). Eles se tornam amigos inseparáveis, até ela ser adotada e deixar o local. Aos 9 anos, Norbit é ameaçado por três garotos da escola mas é salvo por Rasputia (Eddie Murphy), uma robusta garota de 10 anos. Os dois crescem, namoram e se casam. Juntamente com seus irmãos Jack Grandão (Terry Lewis), Azulão (Mighty Rasta) e Earl (Clifton Powell), Rasputia administra a Construtora Latimore. Norbit é empregado da empresa, sendo sempre ridicularizado pelos cunhados. A vida de Norbit não anda nada bem, mas ela muda após reencontrar Kate, que decide comprar o antigo orfanato do sr. Wong. Porém o que Kate não sabe é que seu noivo, Deion (Cuba Gooding Jr.), planeja transformar o local em um bar de strip-tease, contando com a ajuda dos irmãos de Rasputia. Reanimado por ter reencontrado Kate, Norbit ganha confiança e, aos poucos, passa a enfrentar a esposa e sua família.', imagem: 'https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/87/14/10/19872429.jpg' },
          { titulo: 'As Branquelas', descricao: 'Os irmãos Marcus e Kevin Copeland são detetives do FBI que estão com problemas no trabalho. A última investigação da dupla foi um grande fracasso e eles estão sob a ameaça de serem demitidos. Quando um plano para sequestrar as mimadas irmãs Brittany e Tiffany Wilson é descoberto, o caso é entregue aos principais rivais dos irmãos Copeland, os agentes Vincent Gomez e Jack Harper. Para aumentar ainda mais a humilhação da dupla, eles são escalados para escoltar as jovens mimadas do aeroporto até o local de um evento pelo qual elas esperaram por meses. Porém no trajeto um acidente de carro provoca um verdadeiro desastre: enquanto uma das irmãs arranha o nariz, a outra corta o lábio. Desesperadas, elas se recusam a ir ao evento. É quando,para salvar o emprego, Marcus e Kevin decidem por assumir as identidades das irmãs.', imagem: 'https://media.fstatic.com/2w7jxPkN82zyXJWQg9VBcxzB6XI=/210x312/smart/filters:format(webp)/media/movies/covers/2013/03/7c6d04317a06c6cea984d49646fb4d9c_1.jpg' },
          { titulo: 'Os Farofeiros', descricao: 'Colegas de trabalho, Lima, Alexandre, Rocha e Diguinho decidem sair juntos em uma viagem com suas famílias para curtir o feriadão. Entre engarrafamentos quilométricos em carros apertados, ataques de mosquitos e disputas por um espaço na areia de praias lotadas, nada parece dar certo na viagem. Os planos de um passeio perfeito vão definitivamente por água abaixo quando descobrem que a casa que alugaram estava abandonada e caindo aos pedaços. Sem ter para onde ir, eles irão se meter em confusões hilárias e ainda terão que administrar os problemas de convivência para superar aquele que será o feriado mais infernal de suas vidas.', imagem: 'https://media.fstatic.com/Iaht3JVevt5oEilZBHqC_h-u3xY=/210x312/smart/filters:format(webp)/media/movies/covers/2018/01/farofeiros_2.jpg' }
      ];

      default:
        return [];
    }
  }
}
